export enum SortingMode {

    NAME_ASCENDING = 0,
    NAME_DESCENDING = 1,
    LAST_MODIFIED_ASCENDING = 2,
    LAST_MODIFIED_DESCENDING = 3,
    TYPE_ASCENDING = 4,
    TYPE_DESCENDING = 5,
    SIZE_ASCENDING = 6,
    SIZE_DESCENDING = 7
}
